# Generated by Django 5.1.7 on 2025-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_citasprogramadas_fecha_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'ordering': ['especie', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, verbose_name='Peso en KG'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, verbose_name='Peso en KG'),
        ),
        migrations.AlterUniqueTogether(
            name='especie',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='raza',
            unique_together={('especie', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='tiposervicio',
            unique_together={('categoria', 'nombre')},
        ),
    ]
