# Generated by Django 5.1.7 on 2025-04-17 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_fecha_act_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
