# Generated by Django 5.1.7 on 2025-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parametros_sist_alter_servicios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros_sist',
            name='frecuencia_notificacion_cita',
            field=models.IntegerField(default=30, verbose_name='Frecuencia de notificación de cita (en mili segundos)'),
        ),
    ]
