# Generated by Django 5.1.7 on 2025-04-04 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasprogramadas',
            name='fecha_cita',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de la Cita'),
        ),
    ]
