# Generated by Django 5.1.7 on 2025-04-17 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_especie_options_alter_raza_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_act_peso',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
