# Generated by Django 5.1.7 on 2025-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_citasprogramadas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros_sist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_notificacion_cita', models.IntegerField(default=30, verbose_name='Frecuencia de notificación de cita (seg.)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['paciente__historia__nro_hiscli', 'paciente']},
        ),
    ]
